{% set version = "22.1.0.5" %}

package:
  name: wgpu-native
  version: {{ version }}

source:
  url: https://github.com/gfx-rs/wgpu-native/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cdabfa0eb8e9e3187834267eb9401c15a99d0e7d0b1813e0f72bd3d156be5ca8

build:
  number: 1
  run_exports:
    # hmaarrfk: 2023/07/29 -- No clue ....
    - {{ pin_subpackage('wgpu-native', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - pkg-config
    - clangdev
  host:
    - webgpu-headers 0.0.0.2024.6.12
    - clangdev
  run_constrained:
    - webgpu-headers 0.0.0.2024.6.12

test:
  commands:
    - test -f ${PREFIX}/lib/libwgpu_native${SHLIB_EXT}   # [unix]
    - test -f ${PREFIX}/include/wgpu.h                   # [unix]
    - if not exist %PREFIX%\\Library\\lib\\wgpu_native.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\wgpu_native.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\wgpu.h exit 1       # [win]

about:
  home: https://github.com/gfx-rs/wgpu-native
  summary: A native WebGPU implementation in Rust, based on wgpu-core.
  description: |
    The bindings are based on the WebGPU-native header found at
    ffi/webgpu-headers/webgpu.h and wgpu-native specific items in ffi/wgpu.h
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE.MIT
    - LICENSE.APACHE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - hmaarrfk
