azure:
  settings_osx:
    pool:
      vmImage: macos-12
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
bot:
  abi_migration_branches:
    - 0.14
